-- Inserir clientes padrão
INSERT IGNORE INTO site_clients (name, logo_url, is_active) VALUES
('Heineken', '/logos/heineken.png', 1),
('LIESA', '/logos/liesa.png', 1),
('VIBRA', '/logos/vibra.png', 1),
('GH Music', '/logos/ghmusic.png', 1),
('BrasilCap', '/logos/brasilcap.png', 1),
('CEDAE', '/logos/cedae.png', 1),
('Rio Carnaval', '/logos/rio-carnaval.png', 1),
('Levels', '/logos/levels-correct.png', 1),
('Bosque Bar', '/logos/bosque-bar.png', 1),
('Ferro & Brasa', '/logos/ferro-e-brasa.png', 1),
('WeMake', '/logos/wemake.png', 1),
('Virada Sustentável', '/logos/virada-sustentavel.png', 1),
('Rio FutSummit 26', '/logos/rio-futsummit-26.png', 1),
('Sacadura 154', '/logos/sacadura-154.png', 1),
('NMLSS', '/logos/nmlss-correct.png', 1),
('Subsea 7', '/logos/subsea7.png', 1),
('Café Preto Tattoo', '/logos/cafe-preto-tattoo-correct.png', 1),
('FuraTodo', '/logos/fura-toblu.png', 1),
('Salgueiro', '/logos/salgueiro.png', 1),
('Cidaddess', '/logos/cidaddess.png', 1),
('Silimed', '/logos/silimed.png', 1),
('Maltas', '/logos/maltas.png', 1),
('Grupo Onda', '/logos/grupo-onda.png', 1);
