<?php
declare(strict_types=1);

require_once __DIR__ . '/security.php';

/**
 * Chave do Asaas, pelo mesmo caminho que todo o resto do backend usa.
 *
 * Antes esta função carregava `env.php` por conta própria, com `require` (sem
 * `_once`): toda chamada reincluía o arquivo e o PHP avisava "Constant already
 * defined" uma vez por constante. Pior, era um segundo caminho de configuração
 * que não respeitava `ECOLETA_ENV_FILE` — então a suíte lia as credenciais de
 * produção da máquina de quem tinha publicado, e o teste de "sem chave
 * configurada" rodava com a chave real na mão.
 */
function getAsaasApiKey(): string
{
    return apiSecret('ASAAS_API_KEY');
}

function asaasRequest(string $endpoint, string $method = 'GET', array $data = []): array
{
    $apiKey = getAsaasApiKey();
    if (!$apiKey) {
        throw new RuntimeException('ASAAS_API_KEY não configurada.');
    }

    $url = 'https://api.asaas.com/v3' . $endpoint; // Use sandbox if needed, but the user requested production setup via Asaas.com
    
    $ch = curl_init($url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_TIMEOUT, 30);
    curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 10);
    curl_setopt($ch, CURLOPT_HTTPHEADER, [
        'access_token: ' . $apiKey,
        'Content-Type: application/json',
        'User-Agent: EcoletaApp/1.0'
    ]);
    
    if ($method === 'POST') {
        curl_setopt($ch, CURLOPT_POST, true);
        curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($data));
    }
    
    $response = curl_exec($ch);
    $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);
    
    if ($response === false) {
        throw new RuntimeException('Erro na comunicação com o Asaas.');
    }
    
    $decoded = json_decode($response, true);
    
    if ($httpCode >= 400) {
        $errorMsg = 'Erro na API Asaas.';
        if (isset($decoded['errors']) && is_array($decoded['errors']) && count($decoded['errors']) > 0) {
            $errorMsg = $decoded['errors'][0]['description'];
        }
        throw new RuntimeException($errorMsg);
    }
    
    if (!is_array($decoded)) throw new RuntimeException('Resposta inválida do Asaas.');
    return $decoded;
}

function asaasCreateCustomer(string $name, string $email, ?string $document, ?string $phone): string
{
    $data = [
        'name' => $name,
        'email' => $email,
        'cpfCnpj' => $document,
        'mobilePhone' => $phone,
        'notificationDisabled' => true // Prevent Asaas from sending its native emails
    ];
    
    $data = array_filter($data); // Remove nulls
    
    $response = asaasRequest('/customers', 'POST', $data);
    return $response['id'];
}

function asaasUpdateCustomer(string $customerId, array $data): array
{
    return asaasRequest('/customers/' . $customerId, 'POST', $data);
}

function asaasCreatePayment(string $customerId, float $value, string $dueDate): array
{
    $data = [
        'customer' => $customerId,
        'billingType' => 'BOLETO', // Changed from PIX so the client can download a PDF Boleto (Pix is still auto-generated by Asaas)
        'value' => $value,
        'dueDate' => $dueDate,
        'description' => 'Fatura Mensal - Ecoleva'
    ];
    
    $response = asaasRequest('/payments', 'POST', $data);
    
    return [
        'id' => $response['id'],
        'invoiceUrl' => $response['invoiceUrl']
    ];
}

function asaasGetPixQrCode(string $paymentId): array
{
    $response = asaasRequest('/payments/' . $paymentId . '/pixQrCode');
    return [
        'payload' => $response['payload'],
        'encodedImage' => $response['encodedImage']
    ];
}
